name: master-thesis
channels:
  - conda-forge
dependencies:
  # Python interpreter
  - python=3.10
  # pre-commit requirements
  - pre-commit>=2.20.0
  - rust>=1.64.0
  # Latex compiler
  - tectonic>=0.11.0
  # Notebook runner
  - papermill>=2.3.4
  - ipykernel>=6.16.0
  # Notebook converter
  - nbformat>=5.6.1
  - nbconvert>=7.2.1
  - pandoc>=2.19.2
  - pip
  # Requirements to run the notebook which are not on conda-forge
  # Or require a development version directly from git to work
  # - pip:
  #     - dependency==1
